In [8]:
import random, numpy as np
def normalizeRows(x):
    """ Row normalization function

    Implement a function that normalizes each row of a matrix to have
    unit length.
    """

    ### YOUR CODE HERE
    try:
        x_l = np.linalg.norm(x, axis=1, keepdims=True)
        x /= x_l
    except:
        raise NotImplementedError
    ### END YOUR CODE

    return x

random.seed(31415)
np.random.seed(9265)
dummy_vectors = normalizeRows(np.random.randn(10,3))
dummy_tokens = dict([("a",0), ("b",1), ("c",2),("d",3),("e",4)])
dummy_vectors, dummy_tokens

(array([[-0.96735714, -0.02182641,  0.25247529],
        [ 0.73663029, -0.48088687, -0.47552459],
        [-0.27323645,  0.12538062,  0.95374082],
        [-0.56713774, -0.27178229, -0.77748902],
        [-0.59609459,  0.7795666 ,  0.19221644],
        [-0.6831809 , -0.04200519,  0.72904007],
        [ 0.18289107,  0.76098587, -0.62245591],
        [-0.61517874,  0.5147624 , -0.59713884],
        [-0.33867074, -0.80966534, -0.47931635],
        [-0.52629529, -0.78190408,  0.33412466]]),
 {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4})

In [9]:
dummy_vectors[5:,:]

array([[-0.6831809 , -0.04200519,  0.72904007],
       [ 0.18289107,  0.76098587, -0.62245591],
       [-0.61517874,  0.5147624 , -0.59713884],
       [-0.33867074, -0.80966534, -0.47931635],
       [-0.52629529, -0.78190408,  0.33412466]])

In [10]:
pred = np.array([0,0,0,1,0])
np.tile(pred, (5,1))

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]])

In [11]:
pred = np.array([0,0,0,1,0])
np.repeat(pred.reshape((1,5)), 5, axis=0)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]])

In [12]:
%run q1_softmax.py

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!



In [13]:
%run q2_sigmoid.py

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!



In [18]:
%run q2_gradcheck.py

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



In [19]:
%run q2_neural.py

Running sanity check...
Gradient check passed!


In [58]:
%run q3_word2vec.py

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
Gradient check failed.
First gradient error found at index %s


TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'

In [41]:
%run q3_sgd.py

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.414836786079764e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.524451035823933e-09



In [43]:
%run q3_run.py

FileNotFoundError: [Errno 2] No such file or directory: 'utils/datasets/stanfordSentimentTreebank/datasetSentences.txt'

In [62]:
%run q3_word2vec_ver2.py

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.166109001533981, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947339, -1.36873189,  2.45158957],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.41045956,  0.18834851,  1.43272264],
       [ 0.38202831, -0.17530219, -1.33348241],
       [ 0.07009355, -0.03216399, -0.24466386],
       [ 0.09472154, -0.04346509, -0.33062865],
       [-0.13638384,  0.06258276,  0.47605228]]))

(14.572237336084017, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-3.59141411, -3.47757983, -0.50731271],
       [ 0.        ,  0.        ,  0.        ],
       [ 0. 